#!/usr/bin/env bash
# Make a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' >/var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
echo 'Ceci n'est pas une page' | sudo tee /var/www/html/custom_error.html > /dev/null
sudo sed -i '26i error_page 404 /custom_error.html;' /etc/nginx/sites-available/default
sudo service nginx restart
